server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location /usuarios/ {
    rewrite ^/usuarios/(.*)$ /$1 break;
    try_files $uri $uri/ /index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
